### ISSUE TITLE
[suggestion] Convert account credentials to constructor parameters

### ISSUE THREAD

**Issue by cyclotron3k** [hanklords/flickraw#103]
How about moving `api_key` and `shared_secret` from class variables in `FlickRaw` to instance variables in `FlickRaw::Flickr`, then it will be possible to run multiple connections easily?

If you're interested in this idea, I can submit another PR.

**Comment by hanklords** [comment]
It is a good idea.

**Comment by cyclotron3k** [comment]
PR #104 created
