### ISSUE TITLE
[suggestion] Merge FlickRaw::Flickr into FlickRaw

### ISSUE THREAD

**Issue by cyclotron3k** [hanklords/flickraw#105]
...Then we can call `FlickRaw.new` instead of `FlickRaw::Flickr.new`

Also, how about auto-translating Flickr's camel-case endpoints into more idiomatic underscore methods.

E.g. `flickr.photos.get_recent_photos`, instead of `flickr.photos.getRecentPhotos`

**Comment by hanklords** [comment]
1- Fine
2- I think I prefer to keep the same name as on flickr documentation. Also I think it is better to not break people's code by renaming functions.

**Comment by cyclotron3k** [comment]
1. Ok cool I'll have a look at making a PR. BTW, I noticed that the 'Flickr' gem is obsolete. If I can make contact with the maintainers (and persuade them), would you be interested in taking over the 'Flicker' namespace?

2. I figured that because we've already broken backwards compatibility with v1.0.0, this would be a good (and only) opportunity to make changes like this. But that's not a problem if you want to keep things the way they are.
