### ISSUE TITLE
Release new version to RubyGems

### ISSUE THREAD

**Issue by tanyafortuna** [hanklords/flickraw#108]
The last update for gem version was 0.9.9 on 30 June 2016 - can you please release a new version to Rubygems? We are seeing the fixnum error, which you have fixed on master - but a new version has not been released.

`ruby/2.4.0/gems/flickraw-0.9.9/lib/flickraw/response.rb:40: warning: constant ::Fixnum is deprecated`

**Comment by rriemann** [comment]
Yes, a new release would be highly appreciated!

**Comment by hanklords** [comment]
I am not using or maintaining this gem anymore, 
If someone want to take ownership, I would be happy.
I can also publish a new version to rubygems if someone prepare a release.

**Comment by rriemann** [comment]
Dear @tpazitny , you have my full support!

I fear I am not experienced enough to maintain [such a popular gem](https://rubygems.org/gems/flickraw/versions/0.9.9) that processes secrets of any kind. :see_no_evil:

**Comment by hanklords** [comment]
I pushed 0.9.10 which was prepared by @cyclotron3k . Many thanks to him !

**Comment by rriemann** [comment]
Why are those other changes from @cyclotron3k from 2018 in the current master not released? Is it just the missing release PR?

**Comment by cyclotron3k** [comment]
Hi @rriemann, they are breaking changes and will require a major version bump. We wanted to push out a version that existing users could upgrade to without making any changes.

Now that's done, we will be doing further releases, but ultimately we are moving `Flickraw` to `Flickr`. You can see the new version [here](https://rubygems.org/gems/flickr)
