### ISSUE TITLE
FlickRaw::FlickrAppNotConfigured (No API key defined!)

### ISSUE THREAD

**Issue by uybinh** [hanklords/flickraw#109]
When using with Rails 5.2 , Ruby 2.5.1
I get `FlickRaw::FlickrAppNotConfigured (No API key defined!)`
although `FLICKRAW_API_KEY`, `FLICKRAW_SHARED_SECRET` are setup properly

**Comment by cyclotron3k** [comment]
Can you check which version of FlickRaw you're using? I'm assuming you're on v0.9.9.

The documentation currently visible on GitHub is for an unreleased version (v1.0.0) which automatically uses ENV variables, but v0.9.9 does not. You'll need to explicitly set the two variables as per this earlier version of the documentation: https://github.com/hanklords/flickraw/tree/26f350083ee2f5e53cd2f7990af1b3812075c4e5
