### ISSUE TITLE
Cannot create new Flickr object (ArgumentError)

### ISSUE THREAD

**Issue by jamcry** [hanklords/flickraw#112]
I just installed the gem for my rails project. I have stored my keys as environment variables. I tried creating a new object with both
`flickr = FlickRaw::Flickr.new "MY_API_KEY_HERE", "SECRET_KEY_HERE"`
and
`flickr = FlickRaw::Flickr.new`
, but both returned errors (ArgumentError and FlickRaw::FlickrAppNotConfigured respectively).

**Comment by cyclotron3k** [comment]
The documentation you see at the head of the master branch does not match the version of the gem you're using. I assume you're using 0.9.10? The documentation for that is here: https://github.com/hanklords/flickraw/tree/V0.9.10

**Comment by jamcry** [comment]
> The documentation you see at the head of the master branch does not match the version of the gem your using. I assume you're using 0.9.10? The documentation for that is here: https://github.com/hanklords/flickraw/tree/V0.9.10

Yes, you are right. Thank you.
