### ISSUE TITLE
undefined method `keys' for "year":String (NoMethodError)

### ISSUE THREAD

**Issue by gatogatogato** [hanklords/flickraw#115]
I recently keep getting this error

`.../lib/flickraw/response.rb:8:in build: undefined method keys' for "year":String (NoMethodError)`

when calling 

`flickr.photos.getInfo(:photo_id => xxxxxxxxxx) `

And I don't know how to fix it.

**Comment by cyclotron3k** [comment]
Hi gatogatogato,

`Flickraw` was moved to the `Flickr` namespace, and development has continued on https://github.com/cyclotron3k/flickr/

The issue you mention was identified in https://github.com/cyclotron3k/flickr/issues/3 and resolved in https://github.com/cyclotron3k/flickr/pull/4

https://rubygems.org/gems/flickr/ v2.1.0

**Comment by gatogatogato** [comment]
Thank you so much for this. I will adapt my code accordingly. Thank you for keeping this alive!
