### ISSUE TITLE
flickr method defined globally

### ISSUE THREAD

**Issue by w1150n** [hanklords/flickraw#51]
This gem creates an unscoped flickr method.  It interferes with scopes and other things of the same name.  It ends up causing this exception:

"RuntimeError: No API key or secret defined !"

I was able to get around that error by moving the require line from outside the class to inside a method declaration.

**Comment by 9mm** [comment]
The 'flickr' global variable in this is absolutely fucking insane... is it 1992? It's wrong on so many levels that it's painful.

**Comment by 9mm** [comment]
My favorite part is this: `However this is a bug in ActiveRecord, not in flickraw`

Yes, if I douse your house with gasoline and burn it to the ground it MUST be the gasoline manufacturers fault.

**Comment by 9mm** [comment]
I'll see myself out before I make it worse, everyone have a good day. 

<img src="https://media1.giphy.com/media/hn45V8hBhRIpW/giphy.gif">

**Comment by cyclotron3k** [comment]
I can do a PR for the documentation if you like

**Comment by hanklords** [comment]
@cyclotron3k send your PR :)

**Comment by cyclotron3k** [comment]
I created PR #102 :+1:

**Comment by cyclotron3k** [comment]
Done. The changes can't be released as part of the 0.9.x series because they are breaking changes, but they can be found in the `Flickr` gem, version 2.x.x
