### ISSUE TITLE
Flickr Video: Filetype was not recognised

### ISSUE THREAD

**Issue by phlegx** [hanklords/flickraw#80]
For uploading a Video via Flickr API and this gem, which mime types/ application types do work? I tried now `webm` and also `avi` but both do not seem to work.

However, using the Flickr Web-interface, does work just fine for those files.

Any ideas? Thanks!

**Comment by tak1n** [comment]
Using the `content_type` argument like described here works for mp4 videos:

https://www.flickr.com/services/api/upload.api.html

Also tried with ogg videos but it seems flickr doesn't support them and returns a Filetype was not recognised error.
Seems like this can be closed as it is no further an issue with this gem.
