### ISSUE TITLE
SSL exception

### ISSUE THREAD

**Issue by phlegx** [hanklords/flickraw#81]
When I try to upload I get the following exception:

``` ruby
Exception: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

Not sure why this is happening. Any ideas?

**Comment by jamesjohnmcguire** [comment]
I tried installing Class-3-Public-Primary-Certification-Authority.pem with no luck.  Still going on with ruby 2.1.1.6p336.

**Comment by joelxr** [comment]
Hello, I had the same problem and I couldn't fix tis out. I'm using windows machine too.

[]s

**Comment by gep13** [comment]
@joelxr these are the steps I am following on my AppVeyor CI Build:

https://github.com/adnuguk/adnuguk.github.io/blob/source/appveyor.yml#L37

To work around this problem.  Hope that helps!
